version: "3.8"
services:
 web:
  build: ./docker
  ports:
   - 8080:80
  volumes:
   - .:/app
  environment:
   - WEB_DOCUMENT_ROOT=/app/public  
 oracle:
  image: gvenzl/oracle-xe:slim
  ports: 
   - 1522:1521
  environment:
   - ORACLE_PASSWORD=09137528
   - APP_USER=LOJA_HACKADEV
   - APP_USER_PASSWORD=09137528
